"""add role change log

Revision ID: eab2a5ec5d68
Revises: 63c1705d1dfd
Create Date: 2025-05-04 01:06:41.458314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab2a5ec5d68'
down_revision: Union[str, None] = '63c1705d1dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_change_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('target_user_id', sa.UUID(), nullable=False),
    sa.Column('old_role', sa.String(length=50), nullable=True),
    sa.Column('new_role', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_change_logs_id'), 'role_change_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_change_logs_id'), table_name='role_change_logs')
    op.drop_table('role_change_logs')
    # ### end Alembic commands ###
